// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarType.proto

package com.minkyu.yourdailyword.common.protos;

/**
 * Protobuf enum {@code yourdailyword.CalendarType}
 */
public enum CalendarType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>NOT_SPECIFIED = 0;</code>
   */
  NOT_SPECIFIED(0),
  /**
   * <code>GREGORIAN_BASED = 1;</code>
   */
  GREGORIAN_BASED(1),
  /**
   * <code>LUNAR_BASED = 2;</code>
   */
  LUNAR_BASED(2),
  /**
   * <code>HEBREW_BASED = 3;</code>
   */
  HEBREW_BASED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NOT_SPECIFIED = 0;</code>
   */
  public static final int NOT_SPECIFIED_VALUE = 0;
  /**
   * <code>GREGORIAN_BASED = 1;</code>
   */
  public static final int GREGORIAN_BASED_VALUE = 1;
  /**
   * <code>LUNAR_BASED = 2;</code>
   */
  public static final int LUNAR_BASED_VALUE = 2;
  /**
   * <code>HEBREW_BASED = 3;</code>
   */
  public static final int HEBREW_BASED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CalendarType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CalendarType forNumber(int value) {
    switch (value) {
      case 0: return NOT_SPECIFIED;
      case 1: return GREGORIAN_BASED;
      case 2: return LUNAR_BASED;
      case 3: return HEBREW_BASED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CalendarType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CalendarType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CalendarType>() {
          public CalendarType findValueByNumber(int number) {
            return CalendarType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.minkyu.yourdailyword.common.protos.CalendarTypeProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final CalendarType[] VALUES = values();

  public static CalendarType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CalendarType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:yourdailyword.CalendarType)
}

