// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GregorianCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public final class GregorianCalendarOptionsProto {
  private GregorianCalendarOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yourdailyword_GregorianCalendarOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yourdailyword_GregorianCalendarOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036GregorianCalendarOptions.proto\022\ryourda" +
      "ilyword\"P\n\030GregorianCalendarOptions\022\020\n\010s" +
      "etting1\030\001 \001(\010\022\020\n\010setting2\030\002 \001(\010\022\020\n\010setti" +
      "ng3\030\003 \001(\010BI\n&com.minkyu.yourdailyword.co" +
      "mmon.protosB\035GregorianCalendarOptionsPro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yourdailyword_GregorianCalendarOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yourdailyword_GregorianCalendarOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yourdailyword_GregorianCalendarOptions_descriptor,
        new java.lang.String[] { "Setting1", "Setting2", "Setting3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
