// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GregorianCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public interface GregorianCalendarOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yourdailyword.GregorianCalendarOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool setting1 = 1;</code>
   * @return The setting1.
   */
  boolean getSetting1();

  /**
   * <code>bool setting2 = 2;</code>
   * @return The setting2.
   */
  boolean getSetting2();

  /**
   * <code>bool setting3 = 3;</code>
   * @return The setting3.
   */
  boolean getSetting3();
}
