// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HebrewCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public final class HebrewCalendarOptionsProto {
  private HebrewCalendarOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yourdailyword_HebrewCalendarOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yourdailyword_HebrewCalendarOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033HebrewCalendarOptions.proto\022\ryourdaily" +
      "word\"S\n\025HebrewCalendarOptions\022\026\n\016adar_is" +
      "_adar_1\030\001 \001(\010\022\020\n\010setting2\030\002 \001(\010\022\020\n\010setti" +
      "ng3\030\003 \001(\010BF\n&com.minkyu.yourdailyword.co" +
      "mmon.protosB\032HebrewCalendarOptionsProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yourdailyword_HebrewCalendarOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yourdailyword_HebrewCalendarOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yourdailyword_HebrewCalendarOptions_descriptor,
        new java.lang.String[] { "AdarIsAdar1", "Setting2", "Setting3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
