// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HebrewCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public interface HebrewCalendarOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yourdailyword.HebrewCalendarOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool adar_is_adar_1 = 1;</code>
   * @return The adarIsAdar1.
   */
  boolean getAdarIsAdar1();

  /**
   * <code>bool setting2 = 2;</code>
   * @return The setting2.
   */
  boolean getSetting2();

  /**
   * <code>bool setting3 = 3;</code>
   * @return The setting3.
   */
  boolean getSetting3();
}
