// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LunarCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public final class LunarCalendarOptionsProto {
  private LunarCalendarOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yourdailyword_LunarCalendarOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yourdailyword_LunarCalendarOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032LunarCalendarOptions.proto\022\ryourdailyw" +
      "ord\"L\n\024LunarCalendarOptions\022\020\n\010setting1\030" +
      "\001 \001(\010\022\020\n\010setting2\030\002 \001(\010\022\020\n\010setting3\030\003 \001(" +
      "\010BE\n&com.minkyu.yourdailyword.common.pro" +
      "tosB\031LunarCalendarOptionsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yourdailyword_LunarCalendarOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yourdailyword_LunarCalendarOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yourdailyword_LunarCalendarOptions_descriptor,
        new java.lang.String[] { "Setting1", "Setting2", "Setting3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
