// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MultilingualString.proto

package com.minkyu.yourdailyword.common.protos;

public final class MultilingualStringProto {
  private MultilingualStringProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yourdailyword_MultilingualString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yourdailyword_MultilingualString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030MultilingualString.proto\022\ryourdailywor" +
      "d\"%\n\022MultilingualString\022\017\n\007English\030\001 \001(\t" +
      "BC\n&com.minkyu.yourdailyword.common.prot" +
      "osB\027MultilingualStringProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yourdailyword_MultilingualString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yourdailyword_MultilingualString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yourdailyword_MultilingualString_descriptor,
        new java.lang.String[] { "English", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
