// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MultilingualString.proto

package com.minkyu.yourdailyword.common.protos;

public final class MultilingualStringProtos {
  private MultilingualStringProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MultilingualString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MultilingualString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030MultilingualString.proto\"%\n\022Multilingu" +
      "alString\022\017\n\007English\030\001 \001(\tBD\n&com.minkyu." +
      "yourdailyword.common.protosB\030Multilingua" +
      "lStringProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MultilingualString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MultilingualString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MultilingualString_descriptor,
        new java.lang.String[] { "English", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
