// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MultilingualString.proto

package com.minkyu.yourdailyword.common.protos;

public interface MultilingualStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yourdailyword.MultilingualString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string English = 1;</code>
   * @return The english.
   */
  java.lang.String getEnglish();
  /**
   * <code>string English = 1;</code>
   * @return The bytes for english.
   */
  com.google.protobuf.ByteString
      getEnglishBytes();
}
