// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quote.proto

package com.minkyu.yourdailyword.common.protos;

public interface QuoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yourdailyword.Quote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 uid = 1;</code>
   * @return The uid.
   */
  int getUid();

  /**
   * <code>.yourdailyword.MultilingualString value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.yourdailyword.MultilingualString value = 2;</code>
   * @return The value.
   */
  com.minkyu.yourdailyword.common.protos.MultilingualString getValue();
  /**
   * <code>.yourdailyword.MultilingualString value = 2;</code>
   */
  com.minkyu.yourdailyword.common.protos.MultilingualStringOrBuilder getValueOrBuilder();

  /**
   * <code>int32 associatedMonth = 3;</code>
   * @return The associatedMonth.
   */
  int getAssociatedMonth();

  /**
   * <code>int32 associatedDayOfMonth = 4;</code>
   * @return The associatedDayOfMonth.
   */
  int getAssociatedDayOfMonth();

  /**
   * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
   * @return Whether the gregorianCalendarOptions field is set.
   */
  boolean hasGregorianCalendarOptions();
  /**
   * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
   * @return The gregorianCalendarOptions.
   */
  com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions getGregorianCalendarOptions();
  /**
   * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
   */
  com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptionsOrBuilder getGregorianCalendarOptionsOrBuilder();

  /**
   * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
   * @return Whether the lunarCalendarOptions field is set.
   */
  boolean hasLunarCalendarOptions();
  /**
   * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
   * @return The lunarCalendarOptions.
   */
  com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions getLunarCalendarOptions();
  /**
   * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
   */
  com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptionsOrBuilder getLunarCalendarOptionsOrBuilder();

  /**
   * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
   * @return Whether the hebrewCalendarOptions field is set.
   */
  boolean hasHebrewCalendarOptions();
  /**
   * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
   * @return The hebrewCalendarOptions.
   */
  com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions getHebrewCalendarOptions();
  /**
   * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
   */
  com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptionsOrBuilder getHebrewCalendarOptionsOrBuilder();
}
