// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuoteGregorianCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public final class QuoteGregorianCalendarOptionsProto {
  private QuoteGregorianCalendarOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yourdailyword_QuoteGregorianCalendarOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yourdailyword_QuoteGregorianCalendarOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#QuoteGregorianCalendarOptions.proto\022\ry" +
      "ourdailyword\"\\\n\035QuoteGregorianCalendarOp" +
      "tions\022\027\n\017skipOnShortYear\030\001 \001(\010\022\020\n\010settin" +
      "g2\030\002 \001(\010\022\020\n\010setting3\030\003 \001(\010BN\n&com.minkyu" +
      ".yourdailyword.common.protosB\"QuoteGrego" +
      "rianCalendarOptionsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yourdailyword_QuoteGregorianCalendarOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yourdailyword_QuoteGregorianCalendarOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yourdailyword_QuoteGregorianCalendarOptions_descriptor,
        new java.lang.String[] { "SkipOnShortYear", "Setting2", "Setting3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
