// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CalendarType.proto

package com.minkyu.yourdailyword.common.protos;

public final class QuotesTypeProtos {
  private QuotesTypeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022CalendarType.proto\022\ryourdailyword*Y\n\014C" +
      "alendarType\022\021\n\rNOT_SPECIFIED\020\000\022\023\n\017GREGOR" +
      "IAN_BASED\020\001\022\017\n\013LUNAR_BASED\020\002\022\020\n\014HEBREW_B" +
      "ASED\020\003B<\n&com.minkyu.yourdailyword.commo" +
      "n.protosB\020QuotesTypeProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
