// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quotes.proto

package com.minkyu.yourdailyword.common.protos;

/**
 * Protobuf type {@code yourdailyword.Quotes}
 */
public final class Quotes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:yourdailyword.Quotes)
    QuotesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Quotes.newBuilder() to construct.
  private Quotes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Quotes() {
    type_ = 0;
    values_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Quotes();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minkyu.yourdailyword.common.protos.QuotesProtos.internal_static_yourdailyword_Quotes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minkyu.yourdailyword.common.protos.QuotesProtos.internal_static_yourdailyword_Quotes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minkyu.yourdailyword.common.protos.Quotes.class, com.minkyu.yourdailyword.common.protos.Quotes.Builder.class);
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.yourdailyword.CalendarType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.yourdailyword.CalendarType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.minkyu.yourdailyword.common.protos.CalendarType getType() {
    com.minkyu.yourdailyword.common.protos.CalendarType result = com.minkyu.yourdailyword.common.protos.CalendarType.forNumber(type_);
    return result == null ? com.minkyu.yourdailyword.common.protos.CalendarType.UNRECOGNIZED : result;
  }

  public static final int VALUES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.minkyu.yourdailyword.common.protos.Quote> values_;
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.minkyu.yourdailyword.common.protos.Quote> getValuesList() {
    return values_;
  }
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.minkyu.yourdailyword.common.protos.QuoteOrBuilder> 
      getValuesOrBuilderList() {
    return values_;
  }
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  @java.lang.Override
  public int getValuesCount() {
    return values_.size();
  }
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.Quote getValues(int index) {
    return values_.get(index);
  }
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.QuoteOrBuilder getValuesOrBuilder(
      int index) {
    return values_.get(index);
  }

  public static final int GREGORIAN_CALENDAR_OPTIONS_FIELD_NUMBER = 3;
  private com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions gregorianCalendarOptions_;
  /**
   * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
   * @return Whether the gregorianCalendarOptions field is set.
   */
  @java.lang.Override
  public boolean hasGregorianCalendarOptions() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
   * @return The gregorianCalendarOptions.
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions getGregorianCalendarOptions() {
    return gregorianCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
  }
  /**
   * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsOrBuilder getGregorianCalendarOptionsOrBuilder() {
    return gregorianCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
  }

  public static final int LUNAR_CALENDAR_OPTIONS_FIELD_NUMBER = 4;
  private com.minkyu.yourdailyword.common.protos.LunarCalendarOptions lunarCalendarOptions_;
  /**
   * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
   * @return Whether the lunarCalendarOptions field is set.
   */
  @java.lang.Override
  public boolean hasLunarCalendarOptions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
   * @return The lunarCalendarOptions.
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.LunarCalendarOptions getLunarCalendarOptions() {
    return lunarCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
  }
  /**
   * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsOrBuilder getLunarCalendarOptionsOrBuilder() {
    return lunarCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
  }

  public static final int HEBREW_CALENDAR_OPTIONS_FIELD_NUMBER = 5;
  private com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions hebrewCalendarOptions_;
  /**
   * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
   * @return Whether the hebrewCalendarOptions field is set.
   */
  @java.lang.Override
  public boolean hasHebrewCalendarOptions() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
   * @return The hebrewCalendarOptions.
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions getHebrewCalendarOptions() {
    return hebrewCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
  }
  /**
   * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsOrBuilder getHebrewCalendarOptionsOrBuilder() {
    return hebrewCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.minkyu.yourdailyword.common.protos.CalendarType.NOT_SPECIFIED.getNumber()) {
      output.writeEnum(1, type_);
    }
    for (int i = 0; i < values_.size(); i++) {
      output.writeMessage(2, values_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getGregorianCalendarOptions());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getLunarCalendarOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getHebrewCalendarOptions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.minkyu.yourdailyword.common.protos.CalendarType.NOT_SPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    for (int i = 0; i < values_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, values_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getGregorianCalendarOptions());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLunarCalendarOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getHebrewCalendarOptions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minkyu.yourdailyword.common.protos.Quotes)) {
      return super.equals(obj);
    }
    com.minkyu.yourdailyword.common.protos.Quotes other = (com.minkyu.yourdailyword.common.protos.Quotes) obj;

    if (type_ != other.type_) return false;
    if (!getValuesList()
        .equals(other.getValuesList())) return false;
    if (hasGregorianCalendarOptions() != other.hasGregorianCalendarOptions()) return false;
    if (hasGregorianCalendarOptions()) {
      if (!getGregorianCalendarOptions()
          .equals(other.getGregorianCalendarOptions())) return false;
    }
    if (hasLunarCalendarOptions() != other.hasLunarCalendarOptions()) return false;
    if (hasLunarCalendarOptions()) {
      if (!getLunarCalendarOptions()
          .equals(other.getLunarCalendarOptions())) return false;
    }
    if (hasHebrewCalendarOptions() != other.hasHebrewCalendarOptions()) return false;
    if (hasHebrewCalendarOptions()) {
      if (!getHebrewCalendarOptions()
          .equals(other.getHebrewCalendarOptions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (getValuesCount() > 0) {
      hash = (37 * hash) + VALUES_FIELD_NUMBER;
      hash = (53 * hash) + getValuesList().hashCode();
    }
    if (hasGregorianCalendarOptions()) {
      hash = (37 * hash) + GREGORIAN_CALENDAR_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getGregorianCalendarOptions().hashCode();
    }
    if (hasLunarCalendarOptions()) {
      hash = (37 * hash) + LUNAR_CALENDAR_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getLunarCalendarOptions().hashCode();
    }
    if (hasHebrewCalendarOptions()) {
      hash = (37 * hash) + HEBREW_CALENDAR_OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getHebrewCalendarOptions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minkyu.yourdailyword.common.protos.Quotes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minkyu.yourdailyword.common.protos.Quotes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yourdailyword.Quotes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yourdailyword.Quotes)
      com.minkyu.yourdailyword.common.protos.QuotesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minkyu.yourdailyword.common.protos.QuotesProtos.internal_static_yourdailyword_Quotes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minkyu.yourdailyword.common.protos.QuotesProtos.internal_static_yourdailyword_Quotes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minkyu.yourdailyword.common.protos.Quotes.class, com.minkyu.yourdailyword.common.protos.Quotes.Builder.class);
    }

    // Construct using com.minkyu.yourdailyword.common.protos.Quotes.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getValuesFieldBuilder();
        getGregorianCalendarOptionsFieldBuilder();
        getLunarCalendarOptionsFieldBuilder();
        getHebrewCalendarOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
      } else {
        values_ = null;
        valuesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      gregorianCalendarOptions_ = null;
      if (gregorianCalendarOptionsBuilder_ != null) {
        gregorianCalendarOptionsBuilder_.dispose();
        gregorianCalendarOptionsBuilder_ = null;
      }
      lunarCalendarOptions_ = null;
      if (lunarCalendarOptionsBuilder_ != null) {
        lunarCalendarOptionsBuilder_.dispose();
        lunarCalendarOptionsBuilder_ = null;
      }
      hebrewCalendarOptions_ = null;
      if (hebrewCalendarOptionsBuilder_ != null) {
        hebrewCalendarOptionsBuilder_.dispose();
        hebrewCalendarOptionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minkyu.yourdailyword.common.protos.QuotesProtos.internal_static_yourdailyword_Quotes_descriptor;
    }

    @java.lang.Override
    public com.minkyu.yourdailyword.common.protos.Quotes getDefaultInstanceForType() {
      return com.minkyu.yourdailyword.common.protos.Quotes.getDefaultInstance();
    }

    @java.lang.Override
    public com.minkyu.yourdailyword.common.protos.Quotes build() {
      com.minkyu.yourdailyword.common.protos.Quotes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minkyu.yourdailyword.common.protos.Quotes buildPartial() {
      com.minkyu.yourdailyword.common.protos.Quotes result = new com.minkyu.yourdailyword.common.protos.Quotes(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.minkyu.yourdailyword.common.protos.Quotes result) {
      if (valuesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.values_ = values_;
      } else {
        result.values_ = valuesBuilder_.build();
      }
    }

    private void buildPartial0(com.minkyu.yourdailyword.common.protos.Quotes result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.gregorianCalendarOptions_ = gregorianCalendarOptionsBuilder_ == null
            ? gregorianCalendarOptions_
            : gregorianCalendarOptionsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lunarCalendarOptions_ = lunarCalendarOptionsBuilder_ == null
            ? lunarCalendarOptions_
            : lunarCalendarOptionsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.hebrewCalendarOptions_ = hebrewCalendarOptionsBuilder_ == null
            ? hebrewCalendarOptions_
            : hebrewCalendarOptionsBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minkyu.yourdailyword.common.protos.Quotes) {
        return mergeFrom((com.minkyu.yourdailyword.common.protos.Quotes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minkyu.yourdailyword.common.protos.Quotes other) {
      if (other == com.minkyu.yourdailyword.common.protos.Quotes.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (valuesBuilder_ == null) {
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
      } else {
        if (!other.values_.isEmpty()) {
          if (valuesBuilder_.isEmpty()) {
            valuesBuilder_.dispose();
            valuesBuilder_ = null;
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000002);
            valuesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getValuesFieldBuilder() : null;
          } else {
            valuesBuilder_.addAllMessages(other.values_);
          }
        }
      }
      if (other.hasGregorianCalendarOptions()) {
        mergeGregorianCalendarOptions(other.getGregorianCalendarOptions());
      }
      if (other.hasLunarCalendarOptions()) {
        mergeLunarCalendarOptions(other.getLunarCalendarOptions());
      }
      if (other.hasHebrewCalendarOptions()) {
        mergeHebrewCalendarOptions(other.getHebrewCalendarOptions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.minkyu.yourdailyword.common.protos.Quote m =
                  input.readMessage(
                      com.minkyu.yourdailyword.common.protos.Quote.parser(),
                      extensionRegistry);
              if (valuesBuilder_ == null) {
                ensureValuesIsMutable();
                values_.add(m);
              } else {
                valuesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getGregorianCalendarOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getLunarCalendarOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getHebrewCalendarOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.yourdailyword.CalendarType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.yourdailyword.CalendarType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.yourdailyword.CalendarType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.minkyu.yourdailyword.common.protos.CalendarType getType() {
      com.minkyu.yourdailyword.common.protos.CalendarType result = com.minkyu.yourdailyword.common.protos.CalendarType.forNumber(type_);
      return result == null ? com.minkyu.yourdailyword.common.protos.CalendarType.UNRECOGNIZED : result;
    }
    /**
     * <code>.yourdailyword.CalendarType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.minkyu.yourdailyword.common.protos.CalendarType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.yourdailyword.CalendarType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.minkyu.yourdailyword.common.protos.Quote> values_ =
      java.util.Collections.emptyList();
    private void ensureValuesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        values_ = new java.util.ArrayList<com.minkyu.yourdailyword.common.protos.Quote>(values_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.Quote, com.minkyu.yourdailyword.common.protos.Quote.Builder, com.minkyu.yourdailyword.common.protos.QuoteOrBuilder> valuesBuilder_;

    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public java.util.List<com.minkyu.yourdailyword.common.protos.Quote> getValuesList() {
      if (valuesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(values_);
      } else {
        return valuesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public int getValuesCount() {
      if (valuesBuilder_ == null) {
        return values_.size();
      } else {
        return valuesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public com.minkyu.yourdailyword.common.protos.Quote getValues(int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);
      } else {
        return valuesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder setValues(
        int index, com.minkyu.yourdailyword.common.protos.Quote value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder setValues(
        int index, com.minkyu.yourdailyword.common.protos.Quote.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.set(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder addValues(com.minkyu.yourdailyword.common.protos.Quote value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder addValues(
        int index, com.minkyu.yourdailyword.common.protos.Quote value) {
      if (valuesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureValuesIsMutable();
        values_.add(index, value);
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder addValues(
        com.minkyu.yourdailyword.common.protos.Quote.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder addValues(
        int index, com.minkyu.yourdailyword.common.protos.Quote.Builder builderForValue) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.add(index, builderForValue.build());
        onChanged();
      } else {
        valuesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder addAllValues(
        java.lang.Iterable<? extends com.minkyu.yourdailyword.common.protos.Quote> values) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
      } else {
        valuesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder clearValues() {
      if (valuesBuilder_ == null) {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        valuesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public Builder removeValues(int index) {
      if (valuesBuilder_ == null) {
        ensureValuesIsMutable();
        values_.remove(index);
        onChanged();
      } else {
        valuesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public com.minkyu.yourdailyword.common.protos.Quote.Builder getValuesBuilder(
        int index) {
      return getValuesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public com.minkyu.yourdailyword.common.protos.QuoteOrBuilder getValuesOrBuilder(
        int index) {
      if (valuesBuilder_ == null) {
        return values_.get(index);  } else {
        return valuesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public java.util.List<? extends com.minkyu.yourdailyword.common.protos.QuoteOrBuilder> 
         getValuesOrBuilderList() {
      if (valuesBuilder_ != null) {
        return valuesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(values_);
      }
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public com.minkyu.yourdailyword.common.protos.Quote.Builder addValuesBuilder() {
      return getValuesFieldBuilder().addBuilder(
          com.minkyu.yourdailyword.common.protos.Quote.getDefaultInstance());
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public com.minkyu.yourdailyword.common.protos.Quote.Builder addValuesBuilder(
        int index) {
      return getValuesFieldBuilder().addBuilder(
          index, com.minkyu.yourdailyword.common.protos.Quote.getDefaultInstance());
    }
    /**
     * <code>repeated .yourdailyword.Quote values = 2;</code>
     */
    public java.util.List<com.minkyu.yourdailyword.common.protos.Quote.Builder> 
         getValuesBuilderList() {
      return getValuesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.Quote, com.minkyu.yourdailyword.common.protos.Quote.Builder, com.minkyu.yourdailyword.common.protos.QuoteOrBuilder> 
        getValuesFieldBuilder() {
      if (valuesBuilder_ == null) {
        valuesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.Quote, com.minkyu.yourdailyword.common.protos.Quote.Builder, com.minkyu.yourdailyword.common.protos.QuoteOrBuilder>(
                values_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      return valuesBuilder_;
    }

    private com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions gregorianCalendarOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions, com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsOrBuilder> gregorianCalendarOptionsBuilder_;
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     * @return Whether the gregorianCalendarOptions field is set.
     */
    public boolean hasGregorianCalendarOptions() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     * @return The gregorianCalendarOptions.
     */
    public com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions getGregorianCalendarOptions() {
      if (gregorianCalendarOptionsBuilder_ == null) {
        return gregorianCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
      } else {
        return gregorianCalendarOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     */
    public Builder setGregorianCalendarOptions(com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions value) {
      if (gregorianCalendarOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gregorianCalendarOptions_ = value;
      } else {
        gregorianCalendarOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     */
    public Builder setGregorianCalendarOptions(
        com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.Builder builderForValue) {
      if (gregorianCalendarOptionsBuilder_ == null) {
        gregorianCalendarOptions_ = builderForValue.build();
      } else {
        gregorianCalendarOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     */
    public Builder mergeGregorianCalendarOptions(com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions value) {
      if (gregorianCalendarOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          gregorianCalendarOptions_ != null &&
          gregorianCalendarOptions_ != com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.getDefaultInstance()) {
          getGregorianCalendarOptionsBuilder().mergeFrom(value);
        } else {
          gregorianCalendarOptions_ = value;
        }
      } else {
        gregorianCalendarOptionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     */
    public Builder clearGregorianCalendarOptions() {
      bitField0_ = (bitField0_ & ~0x00000004);
      gregorianCalendarOptions_ = null;
      if (gregorianCalendarOptionsBuilder_ != null) {
        gregorianCalendarOptionsBuilder_.dispose();
        gregorianCalendarOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     */
    public com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.Builder getGregorianCalendarOptionsBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getGregorianCalendarOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     */
    public com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsOrBuilder getGregorianCalendarOptionsOrBuilder() {
      if (gregorianCalendarOptionsBuilder_ != null) {
        return gregorianCalendarOptionsBuilder_.getMessageOrBuilder();
      } else {
        return gregorianCalendarOptions_ == null ?
            com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
      }
    }
    /**
     * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions, com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsOrBuilder> 
        getGregorianCalendarOptionsFieldBuilder() {
      if (gregorianCalendarOptionsBuilder_ == null) {
        gregorianCalendarOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions, com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsOrBuilder>(
                getGregorianCalendarOptions(),
                getParentForChildren(),
                isClean());
        gregorianCalendarOptions_ = null;
      }
      return gregorianCalendarOptionsBuilder_;
    }

    private com.minkyu.yourdailyword.common.protos.LunarCalendarOptions lunarCalendarOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.LunarCalendarOptions, com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsOrBuilder> lunarCalendarOptionsBuilder_;
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     * @return Whether the lunarCalendarOptions field is set.
     */
    public boolean hasLunarCalendarOptions() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     * @return The lunarCalendarOptions.
     */
    public com.minkyu.yourdailyword.common.protos.LunarCalendarOptions getLunarCalendarOptions() {
      if (lunarCalendarOptionsBuilder_ == null) {
        return lunarCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
      } else {
        return lunarCalendarOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     */
    public Builder setLunarCalendarOptions(com.minkyu.yourdailyword.common.protos.LunarCalendarOptions value) {
      if (lunarCalendarOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lunarCalendarOptions_ = value;
      } else {
        lunarCalendarOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     */
    public Builder setLunarCalendarOptions(
        com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.Builder builderForValue) {
      if (lunarCalendarOptionsBuilder_ == null) {
        lunarCalendarOptions_ = builderForValue.build();
      } else {
        lunarCalendarOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     */
    public Builder mergeLunarCalendarOptions(com.minkyu.yourdailyword.common.protos.LunarCalendarOptions value) {
      if (lunarCalendarOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          lunarCalendarOptions_ != null &&
          lunarCalendarOptions_ != com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.getDefaultInstance()) {
          getLunarCalendarOptionsBuilder().mergeFrom(value);
        } else {
          lunarCalendarOptions_ = value;
        }
      } else {
        lunarCalendarOptionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     */
    public Builder clearLunarCalendarOptions() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lunarCalendarOptions_ = null;
      if (lunarCalendarOptionsBuilder_ != null) {
        lunarCalendarOptionsBuilder_.dispose();
        lunarCalendarOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     */
    public com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.Builder getLunarCalendarOptionsBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getLunarCalendarOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     */
    public com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsOrBuilder getLunarCalendarOptionsOrBuilder() {
      if (lunarCalendarOptionsBuilder_ != null) {
        return lunarCalendarOptionsBuilder_.getMessageOrBuilder();
      } else {
        return lunarCalendarOptions_ == null ?
            com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
      }
    }
    /**
     * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.LunarCalendarOptions, com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsOrBuilder> 
        getLunarCalendarOptionsFieldBuilder() {
      if (lunarCalendarOptionsBuilder_ == null) {
        lunarCalendarOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.LunarCalendarOptions, com.minkyu.yourdailyword.common.protos.LunarCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsOrBuilder>(
                getLunarCalendarOptions(),
                getParentForChildren(),
                isClean());
        lunarCalendarOptions_ = null;
      }
      return lunarCalendarOptionsBuilder_;
    }

    private com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions hebrewCalendarOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions, com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsOrBuilder> hebrewCalendarOptionsBuilder_;
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     * @return Whether the hebrewCalendarOptions field is set.
     */
    public boolean hasHebrewCalendarOptions() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     * @return The hebrewCalendarOptions.
     */
    public com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions getHebrewCalendarOptions() {
      if (hebrewCalendarOptionsBuilder_ == null) {
        return hebrewCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
      } else {
        return hebrewCalendarOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     */
    public Builder setHebrewCalendarOptions(com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions value) {
      if (hebrewCalendarOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hebrewCalendarOptions_ = value;
      } else {
        hebrewCalendarOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     */
    public Builder setHebrewCalendarOptions(
        com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.Builder builderForValue) {
      if (hebrewCalendarOptionsBuilder_ == null) {
        hebrewCalendarOptions_ = builderForValue.build();
      } else {
        hebrewCalendarOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     */
    public Builder mergeHebrewCalendarOptions(com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions value) {
      if (hebrewCalendarOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          hebrewCalendarOptions_ != null &&
          hebrewCalendarOptions_ != com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.getDefaultInstance()) {
          getHebrewCalendarOptionsBuilder().mergeFrom(value);
        } else {
          hebrewCalendarOptions_ = value;
        }
      } else {
        hebrewCalendarOptionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     */
    public Builder clearHebrewCalendarOptions() {
      bitField0_ = (bitField0_ & ~0x00000010);
      hebrewCalendarOptions_ = null;
      if (hebrewCalendarOptionsBuilder_ != null) {
        hebrewCalendarOptionsBuilder_.dispose();
        hebrewCalendarOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     */
    public com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.Builder getHebrewCalendarOptionsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getHebrewCalendarOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     */
    public com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsOrBuilder getHebrewCalendarOptionsOrBuilder() {
      if (hebrewCalendarOptionsBuilder_ != null) {
        return hebrewCalendarOptionsBuilder_.getMessageOrBuilder();
      } else {
        return hebrewCalendarOptions_ == null ?
            com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
      }
    }
    /**
     * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions, com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsOrBuilder> 
        getHebrewCalendarOptionsFieldBuilder() {
      if (hebrewCalendarOptionsBuilder_ == null) {
        hebrewCalendarOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions, com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsOrBuilder>(
                getHebrewCalendarOptions(),
                getParentForChildren(),
                isClean());
        hebrewCalendarOptions_ = null;
      }
      return hebrewCalendarOptionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:yourdailyword.Quotes)
  }

  // @@protoc_insertion_point(class_scope:yourdailyword.Quotes)
  private static final com.minkyu.yourdailyword.common.protos.Quotes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minkyu.yourdailyword.common.protos.Quotes();
  }

  public static com.minkyu.yourdailyword.common.protos.Quotes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Quotes>
      PARSER = new com.google.protobuf.AbstractParser<Quotes>() {
    @java.lang.Override
    public Quotes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Quotes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Quotes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.Quotes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

