// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quotes.proto

package com.minkyu.yourdailyword.common.protos;

public final class QuotesProtos {
  private QuotesProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yourdailyword_Quotes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yourdailyword_Quotes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Quotes.proto\022\ryourdailyword\032\013Quote.pro" +
      "to\032\022CalendarType.proto\032\036GregorianCalenda" +
      "rOptions.proto\032\032LunarCalendarOptions.pro" +
      "to\032\033HebrewCalendarOptions.proto\"\227\003\n\006Quot" +
      "es\022)\n\004type\030\001 \001(\0162\033.yourdailyword.Calenda" +
      "rType\022$\n\006values\030\002 \003(\0132\024.yourdailyword.Qu" +
      "ote\022P\n\032gregorian_calendar_options\030\003 \001(\0132" +
      "\'.yourdailyword.GregorianCalendarOptions" +
      "H\000\210\001\001\022H\n\026lunar_calendar_options\030\004 \001(\0132#." +
      "yourdailyword.LunarCalendarOptionsH\001\210\001\001\022" +
      "J\n\027hebrew_calendar_options\030\005 \001(\0132$.yourd" +
      "ailyword.HebrewCalendarOptionsH\002\210\001\001B\035\n\033_" +
      "gregorian_calendar_optionsB\031\n\027_lunar_cal" +
      "endar_optionsB\032\n\030_hebrew_calendar_option" +
      "sB8\n&com.minkyu.yourdailyword.common.pro" +
      "tosB\014QuotesProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.minkyu.yourdailyword.common.protos.QuoteProtos.getDescriptor(),
          com.minkyu.yourdailyword.common.protos.CalendarTypeProto.getDescriptor(),
          com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsProto.getDescriptor(),
          com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsProto.getDescriptor(),
          com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsProto.getDescriptor(),
        });
    internal_static_yourdailyword_Quotes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yourdailyword_Quotes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yourdailyword_Quotes_descriptor,
        new java.lang.String[] { "Type", "Values", "GregorianCalendarOptions", "LunarCalendarOptions", "HebrewCalendarOptions", "GregorianCalendarOptions", "LunarCalendarOptions", "HebrewCalendarOptions", });
    com.minkyu.yourdailyword.common.protos.QuoteProtos.getDescriptor();
    com.minkyu.yourdailyword.common.protos.CalendarTypeProto.getDescriptor();
    com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsProto.getDescriptor();
    com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsProto.getDescriptor();
    com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
