// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuoteLunarCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public interface QuoteLunarCalendarOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yourdailyword.QuoteLunarCalendarOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool skipOnShortYear = 1;</code>
   * @return The skipOnShortYear.
   */
  boolean getSkipOnShortYear();

  /**
   * <code>bool skipOnShortMonth = 2;</code>
   * @return The skipOnShortMonth.
   */
  boolean getSkipOnShortMonth();

  /**
   * <code>bool setting3 = 3;</code>
   * @return The setting3.
   */
  boolean getSetting3();
}
