// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuoteHebrewCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public final class QuoteHebrewCalendarOptionsProto {
  private QuoteHebrewCalendarOptionsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yourdailyword_QuoteHebrewCalendarOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_yourdailyword_QuoteHebrewCalendarOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n QuoteHebrewCalendarOptions.proto\022\ryour" +
      "dailyword\"a\n\032QuoteHebrewCalendarOptions\022" +
      "\027\n\017skipOnShortYear\030\001 \001(\010\022\030\n\020skipOnShortM" +
      "onth\030\002 \001(\010\022\020\n\010setting3\030\003 \001(\010BK\n&com.mink" +
      "yu.yourdailyword.common.protosB\037QuoteHeb" +
      "rewCalendarOptionsProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_yourdailyword_QuoteHebrewCalendarOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yourdailyword_QuoteHebrewCalendarOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_yourdailyword_QuoteHebrewCalendarOptions_descriptor,
        new java.lang.String[] { "SkipOnShortYear", "SkipOnShortMonth", "Setting3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
