// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuoteGregorianCalendarOptions.proto

package com.minkyu.yourdailyword.common.protos;

public interface QuoteGregorianCalendarOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yourdailyword.QuoteGregorianCalendarOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool skipOnShortYear = 1;</code>
   * @return The skipOnShortYear.
   */
  boolean getSkipOnShortYear();

  /**
   * <code>bool setting2 = 2;</code>
   * @return The setting2.
   */
  boolean getSetting2();

  /**
   * <code>bool setting3 = 3;</code>
   * @return The setting3.
   */
  boolean getSetting3();
}
