// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quotes.proto

package com.minkyu.yourdailyword.common.protos;

public interface QuotesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:yourdailyword.Quotes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.yourdailyword.CalendarType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.yourdailyword.CalendarType type = 1;</code>
   * @return The type.
   */
  com.minkyu.yourdailyword.common.protos.CalendarType getType();

  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  java.util.List<com.minkyu.yourdailyword.common.protos.Quote> 
      getValuesList();
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  com.minkyu.yourdailyword.common.protos.Quote getValues(int index);
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  java.util.List<? extends com.minkyu.yourdailyword.common.protos.QuoteOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .yourdailyword.Quote values = 2;</code>
   */
  com.minkyu.yourdailyword.common.protos.QuoteOrBuilder getValuesOrBuilder(
      int index);

  /**
   * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
   * @return Whether the gregorianCalendarOptions field is set.
   */
  boolean hasGregorianCalendarOptions();
  /**
   * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
   * @return The gregorianCalendarOptions.
   */
  com.minkyu.yourdailyword.common.protos.GregorianCalendarOptions getGregorianCalendarOptions();
  /**
   * <code>optional .yourdailyword.GregorianCalendarOptions gregorian_calendar_options = 3;</code>
   */
  com.minkyu.yourdailyword.common.protos.GregorianCalendarOptionsOrBuilder getGregorianCalendarOptionsOrBuilder();

  /**
   * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
   * @return Whether the lunarCalendarOptions field is set.
   */
  boolean hasLunarCalendarOptions();
  /**
   * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
   * @return The lunarCalendarOptions.
   */
  com.minkyu.yourdailyword.common.protos.LunarCalendarOptions getLunarCalendarOptions();
  /**
   * <code>optional .yourdailyword.LunarCalendarOptions lunar_calendar_options = 4;</code>
   */
  com.minkyu.yourdailyword.common.protos.LunarCalendarOptionsOrBuilder getLunarCalendarOptionsOrBuilder();

  /**
   * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
   * @return Whether the hebrewCalendarOptions field is set.
   */
  boolean hasHebrewCalendarOptions();
  /**
   * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
   * @return The hebrewCalendarOptions.
   */
  com.minkyu.yourdailyword.common.protos.HebrewCalendarOptions getHebrewCalendarOptions();
  /**
   * <code>optional .yourdailyword.HebrewCalendarOptions hebrew_calendar_options = 5;</code>
   */
  com.minkyu.yourdailyword.common.protos.HebrewCalendarOptionsOrBuilder getHebrewCalendarOptionsOrBuilder();
}
