// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Quote.proto

package com.minkyu.yourdailyword.common.protos;

/**
 * Protobuf type {@code yourdailyword.Quote}
 */
public final class Quote extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:yourdailyword.Quote)
    QuoteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Quote.newBuilder() to construct.
  private Quote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Quote() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Quote();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.minkyu.yourdailyword.common.protos.QuoteProtos.internal_static_yourdailyword_Quote_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.minkyu.yourdailyword.common.protos.QuoteProtos.internal_static_yourdailyword_Quote_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.minkyu.yourdailyword.common.protos.Quote.class, com.minkyu.yourdailyword.common.protos.Quote.Builder.class);
  }

  private int bitField0_;
  public static final int UID_FIELD_NUMBER = 1;
  private int uid_ = 0;
  /**
   * <code>int32 uid = 1;</code>
   * @return The uid.
   */
  @java.lang.Override
  public int getUid() {
    return uid_;
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private com.minkyu.yourdailyword.common.protos.MultilingualString value_;
  /**
   * <code>.yourdailyword.MultilingualString value = 2;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.yourdailyword.MultilingualString value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.MultilingualString getValue() {
    return value_ == null ? com.minkyu.yourdailyword.common.protos.MultilingualString.getDefaultInstance() : value_;
  }
  /**
   * <code>.yourdailyword.MultilingualString value = 2;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.MultilingualStringOrBuilder getValueOrBuilder() {
    return value_ == null ? com.minkyu.yourdailyword.common.protos.MultilingualString.getDefaultInstance() : value_;
  }

  public static final int ASSOCIATEDMONTH_FIELD_NUMBER = 3;
  private int associatedMonth_ = 0;
  /**
   * <code>int32 associatedMonth = 3;</code>
   * @return The associatedMonth.
   */
  @java.lang.Override
  public int getAssociatedMonth() {
    return associatedMonth_;
  }

  public static final int ASSOCIATEDDAYOFMONTH_FIELD_NUMBER = 4;
  private int associatedDayOfMonth_ = 0;
  /**
   * <code>int32 associatedDayOfMonth = 4;</code>
   * @return The associatedDayOfMonth.
   */
  @java.lang.Override
  public int getAssociatedDayOfMonth() {
    return associatedDayOfMonth_;
  }

  public static final int GREGORIANCALENDAROPTIONS_FIELD_NUMBER = 5;
  private com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions gregorianCalendarOptions_;
  /**
   * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
   * @return Whether the gregorianCalendarOptions field is set.
   */
  @java.lang.Override
  public boolean hasGregorianCalendarOptions() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
   * @return The gregorianCalendarOptions.
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions getGregorianCalendarOptions() {
    return gregorianCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
  }
  /**
   * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptionsOrBuilder getGregorianCalendarOptionsOrBuilder() {
    return gregorianCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
  }

  public static final int LUNARCALENDAROPTIONS_FIELD_NUMBER = 6;
  private com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions lunarCalendarOptions_;
  /**
   * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
   * @return Whether the lunarCalendarOptions field is set.
   */
  @java.lang.Override
  public boolean hasLunarCalendarOptions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
   * @return The lunarCalendarOptions.
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions getLunarCalendarOptions() {
    return lunarCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
  }
  /**
   * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptionsOrBuilder getLunarCalendarOptionsOrBuilder() {
    return lunarCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
  }

  public static final int HEBREWCALENDAROPTIONS_FIELD_NUMBER = 7;
  private com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions hebrewCalendarOptions_;
  /**
   * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
   * @return Whether the hebrewCalendarOptions field is set.
   */
  @java.lang.Override
  public boolean hasHebrewCalendarOptions() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
   * @return The hebrewCalendarOptions.
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions getHebrewCalendarOptions() {
    return hebrewCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
  }
  /**
   * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
   */
  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptionsOrBuilder getHebrewCalendarOptionsOrBuilder() {
    return hebrewCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (uid_ != 0) {
      output.writeInt32(1, uid_);
    }
    if (value_ != null) {
      output.writeMessage(2, getValue());
    }
    if (associatedMonth_ != 0) {
      output.writeInt32(3, associatedMonth_);
    }
    if (associatedDayOfMonth_ != 0) {
      output.writeInt32(4, associatedDayOfMonth_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getGregorianCalendarOptions());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getLunarCalendarOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(7, getHebrewCalendarOptions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (uid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, uid_);
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValue());
    }
    if (associatedMonth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, associatedMonth_);
    }
    if (associatedDayOfMonth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, associatedDayOfMonth_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getGregorianCalendarOptions());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLunarCalendarOptions());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getHebrewCalendarOptions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.minkyu.yourdailyword.common.protos.Quote)) {
      return super.equals(obj);
    }
    com.minkyu.yourdailyword.common.protos.Quote other = (com.minkyu.yourdailyword.common.protos.Quote) obj;

    if (getUid()
        != other.getUid()) return false;
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (getAssociatedMonth()
        != other.getAssociatedMonth()) return false;
    if (getAssociatedDayOfMonth()
        != other.getAssociatedDayOfMonth()) return false;
    if (hasGregorianCalendarOptions() != other.hasGregorianCalendarOptions()) return false;
    if (hasGregorianCalendarOptions()) {
      if (!getGregorianCalendarOptions()
          .equals(other.getGregorianCalendarOptions())) return false;
    }
    if (hasLunarCalendarOptions() != other.hasLunarCalendarOptions()) return false;
    if (hasLunarCalendarOptions()) {
      if (!getLunarCalendarOptions()
          .equals(other.getLunarCalendarOptions())) return false;
    }
    if (hasHebrewCalendarOptions() != other.hasHebrewCalendarOptions()) return false;
    if (hasHebrewCalendarOptions()) {
      if (!getHebrewCalendarOptions()
          .equals(other.getHebrewCalendarOptions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid();
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (37 * hash) + ASSOCIATEDMONTH_FIELD_NUMBER;
    hash = (53 * hash) + getAssociatedMonth();
    hash = (37 * hash) + ASSOCIATEDDAYOFMONTH_FIELD_NUMBER;
    hash = (53 * hash) + getAssociatedDayOfMonth();
    if (hasGregorianCalendarOptions()) {
      hash = (37 * hash) + GREGORIANCALENDAROPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getGregorianCalendarOptions().hashCode();
    }
    if (hasLunarCalendarOptions()) {
      hash = (37 * hash) + LUNARCALENDAROPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getLunarCalendarOptions().hashCode();
    }
    if (hasHebrewCalendarOptions()) {
      hash = (37 * hash) + HEBREWCALENDAROPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getHebrewCalendarOptions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.minkyu.yourdailyword.common.protos.Quote parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.minkyu.yourdailyword.common.protos.Quote prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code yourdailyword.Quote}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:yourdailyword.Quote)
      com.minkyu.yourdailyword.common.protos.QuoteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.minkyu.yourdailyword.common.protos.QuoteProtos.internal_static_yourdailyword_Quote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.minkyu.yourdailyword.common.protos.QuoteProtos.internal_static_yourdailyword_Quote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.minkyu.yourdailyword.common.protos.Quote.class, com.minkyu.yourdailyword.common.protos.Quote.Builder.class);
    }

    // Construct using com.minkyu.yourdailyword.common.protos.Quote.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getValueFieldBuilder();
        getGregorianCalendarOptionsFieldBuilder();
        getLunarCalendarOptionsFieldBuilder();
        getHebrewCalendarOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uid_ = 0;
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      associatedMonth_ = 0;
      associatedDayOfMonth_ = 0;
      gregorianCalendarOptions_ = null;
      if (gregorianCalendarOptionsBuilder_ != null) {
        gregorianCalendarOptionsBuilder_.dispose();
        gregorianCalendarOptionsBuilder_ = null;
      }
      lunarCalendarOptions_ = null;
      if (lunarCalendarOptionsBuilder_ != null) {
        lunarCalendarOptionsBuilder_.dispose();
        lunarCalendarOptionsBuilder_ = null;
      }
      hebrewCalendarOptions_ = null;
      if (hebrewCalendarOptionsBuilder_ != null) {
        hebrewCalendarOptionsBuilder_.dispose();
        hebrewCalendarOptionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.minkyu.yourdailyword.common.protos.QuoteProtos.internal_static_yourdailyword_Quote_descriptor;
    }

    @java.lang.Override
    public com.minkyu.yourdailyword.common.protos.Quote getDefaultInstanceForType() {
      return com.minkyu.yourdailyword.common.protos.Quote.getDefaultInstance();
    }

    @java.lang.Override
    public com.minkyu.yourdailyword.common.protos.Quote build() {
      com.minkyu.yourdailyword.common.protos.Quote result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.minkyu.yourdailyword.common.protos.Quote buildPartial() {
      com.minkyu.yourdailyword.common.protos.Quote result = new com.minkyu.yourdailyword.common.protos.Quote(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.minkyu.yourdailyword.common.protos.Quote result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uid_ = uid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = valueBuilder_ == null
            ? value_
            : valueBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.associatedMonth_ = associatedMonth_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.associatedDayOfMonth_ = associatedDayOfMonth_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.gregorianCalendarOptions_ = gregorianCalendarOptionsBuilder_ == null
            ? gregorianCalendarOptions_
            : gregorianCalendarOptionsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lunarCalendarOptions_ = lunarCalendarOptionsBuilder_ == null
            ? lunarCalendarOptions_
            : lunarCalendarOptionsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.hebrewCalendarOptions_ = hebrewCalendarOptionsBuilder_ == null
            ? hebrewCalendarOptions_
            : hebrewCalendarOptionsBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.minkyu.yourdailyword.common.protos.Quote) {
        return mergeFrom((com.minkyu.yourdailyword.common.protos.Quote)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.minkyu.yourdailyword.common.protos.Quote other) {
      if (other == com.minkyu.yourdailyword.common.protos.Quote.getDefaultInstance()) return this;
      if (other.getUid() != 0) {
        setUid(other.getUid());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (other.getAssociatedMonth() != 0) {
        setAssociatedMonth(other.getAssociatedMonth());
      }
      if (other.getAssociatedDayOfMonth() != 0) {
        setAssociatedDayOfMonth(other.getAssociatedDayOfMonth());
      }
      if (other.hasGregorianCalendarOptions()) {
        mergeGregorianCalendarOptions(other.getGregorianCalendarOptions());
      }
      if (other.hasLunarCalendarOptions()) {
        mergeLunarCalendarOptions(other.getLunarCalendarOptions());
      }
      if (other.hasHebrewCalendarOptions()) {
        mergeHebrewCalendarOptions(other.getHebrewCalendarOptions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              uid_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              associatedMonth_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              associatedDayOfMonth_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getGregorianCalendarOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getLunarCalendarOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getHebrewCalendarOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int uid_ ;
    /**
     * <code>int32 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }
    /**
     * <code>int32 uid = 1;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(int value) {
      
      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 uid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      uid_ = 0;
      onChanged();
      return this;
    }

    private com.minkyu.yourdailyword.common.protos.MultilingualString value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.MultilingualString, com.minkyu.yourdailyword.common.protos.MultilingualString.Builder, com.minkyu.yourdailyword.common.protos.MultilingualStringOrBuilder> valueBuilder_;
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     * @return The value.
     */
    public com.minkyu.yourdailyword.common.protos.MultilingualString getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? com.minkyu.yourdailyword.common.protos.MultilingualString.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     */
    public Builder setValue(com.minkyu.yourdailyword.common.protos.MultilingualString value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
      } else {
        valueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     */
    public Builder setValue(
        com.minkyu.yourdailyword.common.protos.MultilingualString.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     */
    public Builder mergeValue(com.minkyu.yourdailyword.common.protos.MultilingualString value) {
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          value_ != null &&
          value_ != com.minkyu.yourdailyword.common.protos.MultilingualString.getDefaultInstance()) {
          getValueBuilder().mergeFrom(value);
        } else {
          value_ = value;
        }
      } else {
        valueBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     */
    public com.minkyu.yourdailyword.common.protos.MultilingualString.Builder getValueBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     */
    public com.minkyu.yourdailyword.common.protos.MultilingualStringOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            com.minkyu.yourdailyword.common.protos.MultilingualString.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.yourdailyword.MultilingualString value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.MultilingualString, com.minkyu.yourdailyword.common.protos.MultilingualString.Builder, com.minkyu.yourdailyword.common.protos.MultilingualStringOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.MultilingualString, com.minkyu.yourdailyword.common.protos.MultilingualString.Builder, com.minkyu.yourdailyword.common.protos.MultilingualStringOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    private int associatedMonth_ ;
    /**
     * <code>int32 associatedMonth = 3;</code>
     * @return The associatedMonth.
     */
    @java.lang.Override
    public int getAssociatedMonth() {
      return associatedMonth_;
    }
    /**
     * <code>int32 associatedMonth = 3;</code>
     * @param value The associatedMonth to set.
     * @return This builder for chaining.
     */
    public Builder setAssociatedMonth(int value) {
      
      associatedMonth_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 associatedMonth = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssociatedMonth() {
      bitField0_ = (bitField0_ & ~0x00000004);
      associatedMonth_ = 0;
      onChanged();
      return this;
    }

    private int associatedDayOfMonth_ ;
    /**
     * <code>int32 associatedDayOfMonth = 4;</code>
     * @return The associatedDayOfMonth.
     */
    @java.lang.Override
    public int getAssociatedDayOfMonth() {
      return associatedDayOfMonth_;
    }
    /**
     * <code>int32 associatedDayOfMonth = 4;</code>
     * @param value The associatedDayOfMonth to set.
     * @return This builder for chaining.
     */
    public Builder setAssociatedDayOfMonth(int value) {
      
      associatedDayOfMonth_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 associatedDayOfMonth = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssociatedDayOfMonth() {
      bitField0_ = (bitField0_ & ~0x00000008);
      associatedDayOfMonth_ = 0;
      onChanged();
      return this;
    }

    private com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions gregorianCalendarOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptionsOrBuilder> gregorianCalendarOptionsBuilder_;
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     * @return Whether the gregorianCalendarOptions field is set.
     */
    public boolean hasGregorianCalendarOptions() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     * @return The gregorianCalendarOptions.
     */
    public com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions getGregorianCalendarOptions() {
      if (gregorianCalendarOptionsBuilder_ == null) {
        return gregorianCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
      } else {
        return gregorianCalendarOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     */
    public Builder setGregorianCalendarOptions(com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions value) {
      if (gregorianCalendarOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        gregorianCalendarOptions_ = value;
      } else {
        gregorianCalendarOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     */
    public Builder setGregorianCalendarOptions(
        com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.Builder builderForValue) {
      if (gregorianCalendarOptionsBuilder_ == null) {
        gregorianCalendarOptions_ = builderForValue.build();
      } else {
        gregorianCalendarOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     */
    public Builder mergeGregorianCalendarOptions(com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions value) {
      if (gregorianCalendarOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          gregorianCalendarOptions_ != null &&
          gregorianCalendarOptions_ != com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.getDefaultInstance()) {
          getGregorianCalendarOptionsBuilder().mergeFrom(value);
        } else {
          gregorianCalendarOptions_ = value;
        }
      } else {
        gregorianCalendarOptionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     */
    public Builder clearGregorianCalendarOptions() {
      bitField0_ = (bitField0_ & ~0x00000010);
      gregorianCalendarOptions_ = null;
      if (gregorianCalendarOptionsBuilder_ != null) {
        gregorianCalendarOptionsBuilder_.dispose();
        gregorianCalendarOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     */
    public com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.Builder getGregorianCalendarOptionsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getGregorianCalendarOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     */
    public com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptionsOrBuilder getGregorianCalendarOptionsOrBuilder() {
      if (gregorianCalendarOptionsBuilder_ != null) {
        return gregorianCalendarOptionsBuilder_.getMessageOrBuilder();
      } else {
        return gregorianCalendarOptions_ == null ?
            com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.getDefaultInstance() : gregorianCalendarOptions_;
      }
    }
    /**
     * <code>optional .yourdailyword.QuoteGregorianCalendarOptions gregorianCalendarOptions = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptionsOrBuilder> 
        getGregorianCalendarOptionsFieldBuilder() {
      if (gregorianCalendarOptionsBuilder_ == null) {
        gregorianCalendarOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteGregorianCalendarOptionsOrBuilder>(
                getGregorianCalendarOptions(),
                getParentForChildren(),
                isClean());
        gregorianCalendarOptions_ = null;
      }
      return gregorianCalendarOptionsBuilder_;
    }

    private com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions lunarCalendarOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptionsOrBuilder> lunarCalendarOptionsBuilder_;
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     * @return Whether the lunarCalendarOptions field is set.
     */
    public boolean hasLunarCalendarOptions() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     * @return The lunarCalendarOptions.
     */
    public com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions getLunarCalendarOptions() {
      if (lunarCalendarOptionsBuilder_ == null) {
        return lunarCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
      } else {
        return lunarCalendarOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     */
    public Builder setLunarCalendarOptions(com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions value) {
      if (lunarCalendarOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lunarCalendarOptions_ = value;
      } else {
        lunarCalendarOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     */
    public Builder setLunarCalendarOptions(
        com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.Builder builderForValue) {
      if (lunarCalendarOptionsBuilder_ == null) {
        lunarCalendarOptions_ = builderForValue.build();
      } else {
        lunarCalendarOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     */
    public Builder mergeLunarCalendarOptions(com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions value) {
      if (lunarCalendarOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          lunarCalendarOptions_ != null &&
          lunarCalendarOptions_ != com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.getDefaultInstance()) {
          getLunarCalendarOptionsBuilder().mergeFrom(value);
        } else {
          lunarCalendarOptions_ = value;
        }
      } else {
        lunarCalendarOptionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     */
    public Builder clearLunarCalendarOptions() {
      bitField0_ = (bitField0_ & ~0x00000020);
      lunarCalendarOptions_ = null;
      if (lunarCalendarOptionsBuilder_ != null) {
        lunarCalendarOptionsBuilder_.dispose();
        lunarCalendarOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     */
    public com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.Builder getLunarCalendarOptionsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getLunarCalendarOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     */
    public com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptionsOrBuilder getLunarCalendarOptionsOrBuilder() {
      if (lunarCalendarOptionsBuilder_ != null) {
        return lunarCalendarOptionsBuilder_.getMessageOrBuilder();
      } else {
        return lunarCalendarOptions_ == null ?
            com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.getDefaultInstance() : lunarCalendarOptions_;
      }
    }
    /**
     * <code>optional .yourdailyword.QuoteLunarCalendarOptions lunarCalendarOptions = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptionsOrBuilder> 
        getLunarCalendarOptionsFieldBuilder() {
      if (lunarCalendarOptionsBuilder_ == null) {
        lunarCalendarOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteLunarCalendarOptionsOrBuilder>(
                getLunarCalendarOptions(),
                getParentForChildren(),
                isClean());
        lunarCalendarOptions_ = null;
      }
      return lunarCalendarOptionsBuilder_;
    }

    private com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions hebrewCalendarOptions_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptionsOrBuilder> hebrewCalendarOptionsBuilder_;
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     * @return Whether the hebrewCalendarOptions field is set.
     */
    public boolean hasHebrewCalendarOptions() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     * @return The hebrewCalendarOptions.
     */
    public com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions getHebrewCalendarOptions() {
      if (hebrewCalendarOptionsBuilder_ == null) {
        return hebrewCalendarOptions_ == null ? com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
      } else {
        return hebrewCalendarOptionsBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     */
    public Builder setHebrewCalendarOptions(com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions value) {
      if (hebrewCalendarOptionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        hebrewCalendarOptions_ = value;
      } else {
        hebrewCalendarOptionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     */
    public Builder setHebrewCalendarOptions(
        com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.Builder builderForValue) {
      if (hebrewCalendarOptionsBuilder_ == null) {
        hebrewCalendarOptions_ = builderForValue.build();
      } else {
        hebrewCalendarOptionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     */
    public Builder mergeHebrewCalendarOptions(com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions value) {
      if (hebrewCalendarOptionsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          hebrewCalendarOptions_ != null &&
          hebrewCalendarOptions_ != com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.getDefaultInstance()) {
          getHebrewCalendarOptionsBuilder().mergeFrom(value);
        } else {
          hebrewCalendarOptions_ = value;
        }
      } else {
        hebrewCalendarOptionsBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     */
    public Builder clearHebrewCalendarOptions() {
      bitField0_ = (bitField0_ & ~0x00000040);
      hebrewCalendarOptions_ = null;
      if (hebrewCalendarOptionsBuilder_ != null) {
        hebrewCalendarOptionsBuilder_.dispose();
        hebrewCalendarOptionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     */
    public com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.Builder getHebrewCalendarOptionsBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getHebrewCalendarOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     */
    public com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptionsOrBuilder getHebrewCalendarOptionsOrBuilder() {
      if (hebrewCalendarOptionsBuilder_ != null) {
        return hebrewCalendarOptionsBuilder_.getMessageOrBuilder();
      } else {
        return hebrewCalendarOptions_ == null ?
            com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.getDefaultInstance() : hebrewCalendarOptions_;
      }
    }
    /**
     * <code>optional .yourdailyword.QuoteHebrewCalendarOptions hebrewCalendarOptions = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptionsOrBuilder> 
        getHebrewCalendarOptionsFieldBuilder() {
      if (hebrewCalendarOptionsBuilder_ == null) {
        hebrewCalendarOptionsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions, com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptions.Builder, com.minkyu.yourdailyword.common.protos.QuoteHebrewCalendarOptionsOrBuilder>(
                getHebrewCalendarOptions(),
                getParentForChildren(),
                isClean());
        hebrewCalendarOptions_ = null;
      }
      return hebrewCalendarOptionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:yourdailyword.Quote)
  }

  // @@protoc_insertion_point(class_scope:yourdailyword.Quote)
  private static final com.minkyu.yourdailyword.common.protos.Quote DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.minkyu.yourdailyword.common.protos.Quote();
  }

  public static com.minkyu.yourdailyword.common.protos.Quote getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Quote>
      PARSER = new com.google.protobuf.AbstractParser<Quote>() {
    @java.lang.Override
    public Quote parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Quote> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Quote> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.minkyu.yourdailyword.common.protos.Quote getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

